### ISSUE TITLE
Reminders craches Rimworld

### ISSUE THREAD

**Issue by TIle7** [MadaraUchiha/Reminders#4]
https://gist.github.com/c5c7cf148bc5be84b46fd6711e482b2d

Hi.
So lets say I set up reminder for 3AM.
At 2:59 game goes to non reposning. And just stays that way.
All the mods are working though you'll see a lot of something regerding C:\Unity..... something. No idea what that is.

**Comment by MadaraUchiha** [comment]
Are you getting errors in the log when the game freezes? Could you provide a HugsLib log from when that happens? (This appears to be from the main menu).

I am seeing you having a harmony error which is normally not good, but I don't see what that would cause the behavior you're experiencing.

**Comment by TIle7** [comment]
[Player.log](https://github.com/MadaraUchiha/Reminders/files/4725956/Player.log)

Here it is.
So tested again.
Normal reminder fine. Reccuring (I set recurring in 0 days 0 hours, to get it always in exactly 24h).

Harmony error probably cause I'm on latest release and Harmony is'nt.
Though I dont have a single mode (around 150 mostly QoL) that dont work.

**Comment by MadaraUchiha** [comment]
Well, if you set it to recur every 0 days and 0 hours, it would just recur infinitely, and make your game stuck. It would recur every 0 ticks (that is, now, forever).

I will add a check to make sure that's not possible, but you should set it to recur every 1 days and 0 hours.

**Comment by TIle7** [comment]
Thanks. I was just beeing dumb...
Keep thinking in minutes... Sorry.

**Comment by MadaraUchiha** [comment]
No worries! It's a case I should have handled (like empty title, or event in the past). It will be added in the next patch! Thanks for the report :)
